Repository ncloudcamp16-team3/ncamp16-team3-back, pull requests merged in 2025-04, with the labels that each got.

#6 [ADD] admin 로그인 1차구현/application.yml 수정
  .gitignore
  src/main/java/tf/tailfriend/admin/controller/AdminController.java
  src/main/java/tf/tailfriend/admin/dto/AdminLoginRequest.java
  src/main/java/tf/tailfriend/admin/dto/AdminLoginResponse.java
  src/main/java/tf/tailfriend/admin/repository/AdminDao.java
  src/main/java/tf/tailfriend/admin/service/AdminService.java
  src/main/java/tf/tailfriend/global/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Feat

#8 [FEAT] 로그인,회원가입 구현
  build.gradle
  src/main/java/tf/tailfriend/facility/entity/Facility.java
  src/main/java/tf/tailfriend/file/entity/File.java
  src/main/java/tf/tailfriend/file/repository/FileRepository.java
  src/main/java/tf/tailfriend/global/config/Config.java
  src/main/java/tf/tailfriend/global/config/JwtAuthenticationFilter.java
  src/main/java/tf/tailfriend/global/config/JwtTokenProvider.java
  src/main/java/tf/tailfriend/global/config/OAuth2AttributeExtractor.java
  src/main/java/tf/tailfriend/global/config/OAuth2SuccessHandler.java
  src/main/java/tf/tailfriend/global/config/SecurityConfig.java
  src/main/java/tf/tailfriend/global/config/UserPrincipal.java
  src/main/java/tf/tailfriend/pet/repository/PetPhotoRepository.java
  src/main/java/tf/tailfriend/pet/repository/PetRepository.java
  src/main/java/tf/tailfriend/pet/repository/PetTypeRepository.java
  src/main/java/tf/tailfriend/user/controller/AuthController.java
  src/main/java/tf/tailfriend/user/controller/UserController.java
  src/main/java/tf/tailfriend/user/entity/User.java
  src/main/java/tf/tailfriend/user/entity/dto/LoginRequestDto.java
  src/main/java/tf/tailfriend/user/entity/dto/PetPhotoDto.java
  src/main/java/tf/tailfriend/user/entity/dto/PetRegisterDto.java
  src/main/java/tf/tailfriend/user/entity/dto/UserRegisterDto.java
  src/main/java/tf/tailfriend/user/repository/SnsTypeRepository.java
  src/main/java/tf/tailfriend/user/repository/UserDto.java
  src/main/java/tf/tailfriend/user/repository/UserRepository.java
  src/main/java/tf/tailfriend/user/service/AuthService.java
  src/main/java/tf/tailfriend/user/service/UserService.java
Labels: Feat

#13 [FIX] admin 로그인 수정
  src/main/java/tf/tailfriend/admin/controller/AdminController.java
  src/main/java/tf/tailfriend/admin/service/AdminService.java
  src/main/java/tf/tailfriend/global/config/JwtAuthenticationFilter.java
  src/main/java/tf/tailfriend/global/config/SecurityConfig.java
Labels: Fix

#36 [FEAT] 결제내역 리스트 출력기능 구현
  src/main/java/tf/tailfriend/facility/entity/Facility.java
  src/main/java/tf/tailfriend/reserve/controller/PaymentController.java
  src/main/java/tf/tailfriend/reserve/controller/ReserveController.java
  src/main/java/tf/tailfriend/reserve/dto/ListResponseDto.java
  src/main/java/tf/tailfriend/reserve/dto/PaymentInfoResponseDto.java
  src/main/java/tf/tailfriend/reserve/dto/PaymentListRequestDto.java
  src/main/java/tf/tailfriend/reserve/repository/CustomPaymentDao.java
  src/main/java/tf/tailfriend/reserve/repository/PaymentDao.java
  src/main/java/tf/tailfriend/reserve/repository/PaymentDaoImpl.java
  src/main/java/tf/tailfriend/reserve/repository/ReserveDao.java
  src/main/java/tf/tailfriend/reserve/service/PaymentService.java
Labels: Feat

#42 [FEAT] 공지 작성 1차
  src/main/java/tf/tailfriend/admin/controller/AdminAnnounceController.java
  src/main/java/tf/tailfriend/admin/controller/AdminController.java
  src/main/java/tf/tailfriend/admin/dto/AnnounceResponseDto.java
  src/main/java/tf/tailfriend/admin/entity/Announce.java
  src/main/java/tf/tailfriend/admin/exception/ExistEmailException.java
  src/main/java/tf/tailfriend/admin/message/error/ErrorMessage.java
  src/main/java/tf/tailfriend/admin/repository/AnnounceDao.java
  src/main/java/tf/tailfriend/admin/service/AdminService.java
  src/main/java/tf/tailfriend/admin/service/AnnounceService.java
  src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java
  src/main/java/tf/tailfriend/board/entity/Board.java
  src/main/java/tf/tailfriend/board/entity/BoardLike.java
  src/main/java/tf/tailfriend/board/repository/BoardTypeDao.java
  src/main/java/tf/tailfriend/board/service/BoardService.java
  src/main/java/tf/tailfriend/board/service/BoardTypeService.java
  src/main/java/tf/tailfriend/board/service/CommentService.java
  src/main/java/tf/tailfriend/file/service/FileService.java
  src/main/java/tf/tailfriend/global/config/JwtAuthenticationFilter.java
  src/main/java/tf/tailfriend/global/config/JwtTokenProvider.java
  src/main/java/tf/tailfriend/global/config/SecurityConfig.java
  src/main/java/tf/tailfriend/petsta/entity/PetstaLike.java
  src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java
  src/main/java/tf/tailfriend/user/service/UserService.java
  src/main/resources/application.yml
Labels: Feat

#52 [FEAT] 펫시터/게시판 목록 썸네일 표시
  src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java
  src/main/java/tf/tailfriend/board/service/BoardService.java
  src/main/java/tf/tailfriend/facility/entity/Facility.java
  src/main/java/tf/tailfriend/petsitter/dto/PetSitterResponseDto.java
  src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
Labels: Feat

#51 [FEAT]마이페이지 조회/수정/삭제/추가
  src/main/java/tf/tailfriend/pet/controller/PetController.java
  src/main/java/tf/tailfriend/pet/entity/Pet.java
  src/main/java/tf/tailfriend/pet/entity/dto/PetDetailResponseDto.java
  src/main/java/tf/tailfriend/pet/entity/dto/PetRequestDto.java
  src/main/java/tf/tailfriend/pet/repository/PetTypeDao.java
  src/main/java/tf/tailfriend/pet/service/PetService.java
  src/main/java/tf/tailfriend/user/controller/MemberController.java
  src/main/java/tf/tailfriend/user/repository/UserDao.java
  src/main/java/tf/tailfriend/user/service/MemberService.java
Labels: Feat

#62 [FEAT] 펫시터리스트 applyAt 조건 추가
  src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java
  src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java
  src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
Labels: Feat

#65 [FEAT] 펫시터 신청목록 구현
  src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java
Labels: Feat

#73 [FEAT] 펫시터 승인/반려/삭제 구현
  build.gradle
  src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java
  src/main/java/tf/tailfriend/petsitter/dto/PetSitterResponseDto.java
  src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java
  src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java
  src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
Labels: Feat, Fix

#101 [FIX] 관리자 페이지 전체적으로 수정
  src/main/java/tf/tailfriend/admin/controller/AdminBoardController.java
  src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java
  src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java
  src/main/java/tf/tailfriend/board/repository/BoardDao.java
  src/main/java/tf/tailfriend/board/service/BoardService.java
  src/main/java/tf/tailfriend/facility/dto/FacilityResponseDto.java
  src/main/java/tf/tailfriend/facility/entity/Facility.java
  src/main/java/tf/tailfriend/facility/repository/FacilityDao.java
  src/main/java/tf/tailfriend/facility/repository/FacilityTypeDao.java
  src/main/java/tf/tailfriend/facility/service/FacilityService.java
  src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java
  src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
Labels: Fix

#111 [MODIFY] 마이페이지 펫시터 수정
  src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java
  src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java
  src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java
  src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
  src/main/java/tf/tailfriend/user/controller/UserController.java
Labels: Modify

#112 [FEAT] 업체 등록 페이지 1차
  build.gradle
  src/main/java/tf/tailfriend/admin/controller/AdminBoardController.java
  src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java
  src/main/java/tf/tailfriend/board/service/BoardService.java
  src/main/java/tf/tailfriend/facility/dto/FacilityAddResponseDto.java
  src/main/java/tf/tailfriend/facility/dto/FacilityRequestDto.java
  src/main/java/tf/tailfriend/facility/entity/Facility.java
  src/main/java/tf/tailfriend/facility/repository/FacilityPhotoDao.java
  src/main/java/tf/tailfriend/facility/repository/FacilityTimetableDao.java
  src/main/java/tf/tailfriend/facility/service/FacilityService.java
  src/main/resources/application.yml
Labels: Feat

#129 [ADD] 펫시터 검열 및 상세보기
  src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java
  src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
Labels: Feat

#132 [FIX] 예약 파트 시설목록 페이지 2차
  src/main/java/tf/tailfriend/facility/entity/Facility.java
  src/main/java/tf/tailfriend/facility/entity/FacilityPhoto.java
  src/main/java/tf/tailfriend/facility/entity/dto/FacilityTimetableDto.java
  src/main/java/tf/tailfriend/facility/entity/dto/FacilityTypeDto.java
  src/main/java/tf/tailfriend/facility/entity/dto/forReserve/FacilityCardResponseDto.java
  src/main/java/tf/tailfriend/facility/entity/dto/forReserve/FacilitySimpleDto.java
  src/main/java/tf/tailfriend/facility/entity/dto/forReserve/FacilityWithDistanceProjection.java
  src/main/java/tf/tailfriend/facility/entity/dto/forReserve/Test.java
  src/main/java/tf/tailfriend/facility/entity/dto/forReserve/ThumbnailForCardDto.java
  src/main/java/tf/tailfriend/facility/repository/FacilityDao.java
  src/main/java/tf/tailfriend/facility/repository/FacilityPhotoDao.java
  src/main/java/tf/tailfriend/facility/repository/FacilityTimetableDao.java
  src/main/java/tf/tailfriend/facility/service/FacilityService.java
  src/main/java/tf/tailfriend/global/service/DateTimeFormatProvider.java
  src/main/java/tf/tailfriend/global/service/DateTimeFormatProviderImpl.java
  src/main/java/tf/tailfriend/reserve/controller/PaymentController.java
  src/main/java/tf/tailfriend/reserve/controller/ReserveController.java
  src/main/java/tf/tailfriend/reserve/dto/Card.java
  src/main/java/tf/tailfriend/reserve/dto/DateTimeRange.java
  src/main/java/tf/tailfriend/reserve/dto/ListResponseDto.java
  src/main/java/tf/tailfriend/reserve/dto/PaymentInfoResponseDto.java
  src/main/java/tf/tailfriend/reserve/dto/PaymentListRequestDto.java
  src/main/java/tf/tailfriend/reserve/dto/RequestForFacility/FacilityList.java
  src/main/java/tf/tailfriend/reserve/repository/PaymentDaoImpl.java
  src/main/java/tf/tailfriend/reserve/repository/ReserveDao.java
  src/main/java/tf/tailfriend/reserve/service/PaymentService.java
  src/main/java/tf/tailfriend/reserve/service/ReserveService.java
  src/main/resources/application.yml
Labels: Fix
